#!/usr/bin/env bash
# https://github.com/rileyrg/linux-init/blob/master/directories/bin/sway/waybar-ip-info-json
ifname="${1:-$(printf '%s' /sys/class/net/*/wireless | cut -d/ -f5)}"
[ -z "$ifname" ] && exit 1
pubip="$(curl -s -m 1 ipinfo.io/ip)"
pubip="$([ -z "$pubip" ] && echo "Offline" || echo "$pubip")"
lip=$(ip -j address | jq -r '.[] | select (.ifname=='\"$ifname\"').addr_info[] | select(.family=="inet").local')
lip="$([ -z "$lip" ] && echo -n "Offline" || echo -n "$lip")"
ssid="$(nmcli -t connect show --active|awk -F: '{ if ($3 ~ ".*wireless") print $1; }')"
jq --unbuffered --compact-output -n \
   --arg text " $ssid" \
   --arg alt "$ifname:🌎$pubip,🔌$lip" \
   --arg tooltip "$ifname:🌎$pubip,🔌$lip" \
   --arg class "" \
   --arg percentage "1" \
   --arg ifname "$ifname" \
   --arg ssid "$ssid" \
   --arg public_ip "$pubip" \
   --arg ippadr "$lip" \
   '{text: $text, alt: $alt, tooltip: $tooltip, class: $class, percentage: $percentage, ifname: $ifname, ssid: $ssid, public_ip: $public_ip, ipaddr: $ippadr}'
