#!/bin/bash
kupfer --no-splash &
gnome-settings-daemon &
#gnome-power-manager &
#gnome-screensaver &
#cgmailservice &
#conky -d &
nm-applet &

#nautilus --no-desktop -n &

#~/bin/x11-auto.sh

#ssh-add -L | grep -q chmouel || ssh-add < /dev/null
