#!/bin/bash
kupfer --no-splash &
${HOME}/.dropbox-dist/dropboxd &
gnome-screensaver &
nm-applet &
xfce4-power-manager &
xfce4-volumed &
xscreensaver -no-splash &

#cgmailservice &
#conky -d &
#nautilus --no-desktop -n &
#~/bin/x11-auto.sh
#ssh-add -L | grep -q chmouel || ssh-add < /dev/null
